### ISSUE TITLE
Instructions on getting up and running

### ISSUE THREAD

**Issue by AesSedai101** [refstudycentre/rsc_library#15]
A document explaining how to get contributors up and running.

For example:
- Where to find instructions on installing Drupal
- How to set up the RSC locally
- How to install the cloned modules

**Comment by AesSedai101** [comment]
(Specifically, I need help getting up and running :blush: )

**Comment by rudolfbyker** [comment]
I'm working on a user manual for this! It's hosted privately, because it
contains sensitive information. Will send it to you next week.

2016-05-26 15:03 GMT+02:00 Elsabe Ros notifications@github.com:

**Comment by AesSedai101** [comment]
Awesome, thanks!

**Comment by rudolfbyker** [comment]
The plan is to move that document to the RSC WIKI. @krokkie is also working on a development environment that is easily set up using Vagrant.
